### ISSUE TITLE
PM2.5 Faster Readout

### ISSUE THREAD

**Issue by sibero80** [rytilahti/python-miio#111]
Hello everyone, greetings from Colombia!
I'm trying to figure out the best way to create a listener service that can have a short polling interval from the PM2.5 sensor data.

Executing the command `miio --control 192.168.0.22 --method get_prop --params '["aqi","power","battery","usb_state"]'` provides de desired information, but it takes too long to process (I'm assuming there is some initialization done each time the _miio_ command is executed).

Any suggestins on how to implement a more quick/efficient sensor readout using this library?

thank you!

**Comment by syssi** [comment]
Why do you need more speed? Does the sensor (PM2.5) update so frequently? :-)

**Comment by sibero80** [comment]
That is a great question! I'm trying to implement a makeshift computer vision for cars and PM2.5 correlation. So refresh rate improvements would be great at any level!
I'm asking this because I see that the screen of the device is refreshing at a faster rate than the bash script is pulling.

If discovering a python mechanism what would elliminate any overhead in the readout of the sensor ouput, at least by a 20% - 30%, it would mean a huge improvement for the computer vision project.

I think my question can also be interpreted as this:
Where can I see code examples on how to get device information using python, where all dependencies are only loaded once, and elliminate most of the overhead for continous readout.

Thank you all!

**Comment by rytilahti** [comment]
I think it makes sense to create your own script for your use-case (which was interesting to hear, btw!), but unfortunaly(?) there is no currently way to say whether the handshake is done as a part of communication. The basic workflow would however look like this, which would assuming there are no other limitations on the device would go like this:
1. Initial discovery handshake (which is done currently every time something is sent out)
2. Keep polling the device until the time limit hits (the device will stop answering to requests if there has been no handshake for a while, but can't recall the details, e.g. https://github.com/aholstenson/miio/ does handshake only every X minutes)
3. Do a handshake only when necessary.

Adding a cache instead of sending a handshake for every request is something we could merge assuming it won't break anything. Making it send the handshake for each requests was just an easy way out at that point.

**Comment by sibero80** [comment]
Thank you rytilahti! Your points make a lot of sense.  I was hoping to find out an out-of the box, but it seems I'll have to get my hands dirty as I'm not yet well enough versed in Python, but the challenge is thrilling.  Closing the issue!
