### ISSUE TITLE
Unknown model yeelink.light.color5

### ISSUE THREAD

**Issue by deepdarkmans** [rytilahti/python-miio#1216]
**Device information:**

  - Xiaomi Mi Smart LED Bulb Essential (MJDPL01YL)
[  yandex market product page](https://market.yandex.ru/product--lampa-svetodiodnaia-xiaomi-mi-smart-led-bulb-essential-mjdpl01yl-e27-9vt-6500-k/662471168?sku=662471168&cpa=1)

Model: yeelink.light.color5
Hardware version: esp8266
Firmware version: 2.0.8_0022

**Comment by deepdarkmans** [comment]
this device fully works with all the functions of your library

**Comment by rytilahti** [comment]
Fixed by #1242.

**Comment by rytilahti** [comment]
Are the devices in the same network? The timeout happens when the device doesn't respond for a reason or another, the reason can be anything from the setup of your network to some device-specific issues (e.g., some devices do not respond if they are in another network: https://python-miio.readthedocs.io/en/latest/troubleshooting.html#discover-devices-across-subnets).

Is discovery working with `miiocli discover --handshake` or `miiocli discover --handshake --network 192.168.1.255` (if targeting specific network)?

**Comment by avielc** [comment]
So I worked on that for 4 hours last night to figure it out .
When the device (Xiaomi Mi Smart Led Essential) was reset,  `miiocli discover` did find and received an auto-token of the needed device. 
However after continuing to add it to the Xiaomi Mi Home App. I started getting timeouts to the device.

Eventually my saviour appeared in the form of homebridge-miot plugin which basically lets me sync up devices directly from micloud. best solution for everything

Thanks for answering by the way!
