### ISSUE TITLE
Xiaomi Philips LED Ceiling Lamp 500mm is working

### ISSUE THREAD

**Issue by AndyZ2121** [rytilahti/python-miio#1323]
**Device information:**

  - Name(s) of the device: Xiaomi Philips LED Ceiling Lamp 500mm
  - Link: https://xiaomi-rus.com/umnyy_svetilnik_xiaomi_philips_led_ceiling_lamp/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: 9290013766
  - Hardware version:
  - Firmware version:
  -

**Comment by rytilahti** [comment]
There is no model information here, you'd have to execute `miiocli device --ip <addr> --token <info> info` to get that. I'm closing this now, but please reopen this with the updated model information so we can add the model to the list of supported ones. Thanks!

**Comment by AndyZ2121** [comment]
Please tell me, for the last 2 days, the chandelier has been constantly disconnected from the integration for a few minutes, then it connects for 5 seconds and turns off again. Does it have something to do with these issues? It worked perfectly until February 15. Thanks.

**Comment by rytilahti** [comment]
This is using `miiocli` or something else? Unfortunately I don't know an answer to your question, especially as I don't even know which integration this concerns and how have you installed python-miio. There has been no releases since December, so maybe the firmware of the device has been updated and it has some issues?
