### ISSUE TITLE
Viomi V2 supported

### ISSUE THREAD

**Issue by liorsh69** [rytilahti/python-miio#1339]
Hi, Please add Viomi V2(viomi.vacuum.v6) to the supported device list.
Work using [Homeassistant Vacuum Viomi integration](https://github.com/nergal/homeassistant-vacuum-viomi) from HACS.

  - Name(s) of the device: Viomi V2
  - Link: https://www.viomi.com/robot-vacuums/viomi-v2-pro

  - Model: viomi.vacuum.v6
  - Hardware version: Linux
  - Firmware version: 3.5.8_0046

**Comment by rytilahti** [comment]
Could you please test if it's working with `miiocli` command, outside that custom integration?

Otherwise, you need to report this to that custom integration maintainer (adding `_supported_models` to https://github.com/nergal/homeassistant-vacuum-viomi/blob/master/custom_components/xiaomi_viomi/vacuum.py#L93).

**Comment by liorsh69** [comment]
> Could you please test if it's working with `miiocli` command, outside that custom integration?
> 
> Otherwise, you need to report this to that custom integration maintainer (adding `_supported_models` to https://github.com/nergal/homeassistant-vacuum-viomi/blob/master/custom_components/xiaomi_viomi/vacuum.py#L93).

Working with `miiocli` cli directly from my PC.

**Comment by rytilahti** [comment]
Thanks for reporting & testing, @liorsh69! :+1:
