### ISSUE TITLE
New release 

### ISSUE THREAD

**Issue by KitHubek** [rytilahti/python-miio#1463]
hello, is planned new release date? Last release was over 4 months ago and i see from this time list of bugfixes etc. is very long

**Comment by rytilahti** [comment]
I'm planning to do a release by the end of this weekend, there is already a milestone and a release PR if you wish to follow the process!

**Comment by bobofruit1970** [comment]
Hi, rytilahti 

In connection with this new release that you mention the following services:

xiaomi_miio_airconditioningcompanion.climate_send_command
xiaomi_miio_airconditioningcompanion: climate_learn_command

will they start working again without logging "loop attribute" errors due to python 3.10?

Sorry if this is a stupid question, but I still don't know enough to understand all the dependencies between the parts of HA that you gentlemen are responsible for.

I wonder if it is after the corrections You rytilahti  introduce my problem should be solved or should I have to wait for possible syssi fixes in its xiaomi_airconditioningcompanion integration.

I use above services in my scripts and due to errors (loop attribute) my scripts cannot terminate properly and there are serious problems with my air-conditioning  automation.
I had to go back to the June working release and now I wonder when I should try upgrade again.
Whether after the corrections in [python-miio] You have mentioned or only after syssi fixes in its integration.

Problem reported to syssi.
https://github.com/syssi/xiaomi_airconditioningcompanion/issues/153

**Comment by rytilahti** [comment]
0.5.12 is now out: https://github.com/rytilahti/python-miio/releases/tag/0.5.12

**Comment by KitHubek** [comment]
is some info when this new release will be included in Home Assistant?
Today i see new version HA and in release notes this python-miio update not included

**Comment by rytilahti** [comment]
On the 2022.8 release, the changes done for this release were too numerous to try to push it into a point release. The beta for 2022.8 will start soon (the cutoff is tomorrow), so I'm hoping to get some feedback in the coming few days to see if we need to do some bug fixing :-)
