### ISSUE TITLE
Found an unsupported model 'roborock.vacuum.a01' for class 'RoborockVacuum'

### ISSUE THREAD

**Issue by jack5mikemotown** [rytilahti/python-miio#1707]
Found an unsupported model 'roborock.vacuum.a01' for class 'RoborockVacuum'. If this is working for you, please open an issue.

This is the Roborock E4. Not sure if there's any other information you'd like.

**Comment by rytilahti** [comment]
Thanks for reporting, this is added in #1582 but there has been no new release since then, so this warning will disappear after that gets done. If you don't mind, feel free to run the `get_fw_features` raw command and submit the output to https://github.com/marcelrv/XiaomiRobotVacuumProtocol/blob/master/fw_features.md#firmware-features .

**Comment by autopower** [comment]
On mine the only output is [102]
