### ISSUE TITLE
Add tests for the protocol / usage of construct

### ISSUE THREAD

**Issue by syssi** [rytilahti/python-miio#218]

**Comment by arekbulski** [comment]
See #222 .

I am the developer of Construct and also co-maintainer of Kaitai (its Python runtime), so please take these words with a bit of bias (towards my own project) but also a bit of accuracy. Its true that Kaitai is much more stable than Construct, but its also true that Kaitai has less features. After few years of development they dont have half the features that Construct does, and since their project is much larger/heavier, Construct is getting even more ahead of them. The only drawback is API needs to be broken in the process, but it is well worth it. KSY never had breakage because they dont have enough features yet.

**Comment by arekbulski** [comment]
Someone suggested that maybe you should have a test suite for construct, let me give you two opposite answers with reasons: Yes, because construct never promised backwards/forwards compatibility. API changes whenever there is a good reason to change it. But from this point forward, I will make best effort to get your code uptodate with every release. So No as in no need?

**Comment by arekbulski** [comment]
You mean its not all my fault. :smile: Yeah thanks. I will help you fix construct issues tho.
