### ISSUE TITLE
Add support for Xiaomi Philips Zhirui Smart LED Bulb E14 Candle Lamp

### ISSUE THREAD

**Issue by syssi** [rytilahti/python-miio#243]
The device has the same features as the Philips Bulb. Just the model name will be needed probably. I bought one today.

**Comment by subzero79** [comment]
Home assistant reports  philips.light.candle2 and the link to issues here

Also the token stored in the iOS backup is 96 characters, not 32 like the vacuum cleaner shows in the https://home-assistant.io/components/vacuum.xiaomi_miio/#retrieving-the-access-token

Let me know if you need any more info

**Comment by syssi** [comment]
The 96 char token can be decrypted by miio-extract-tokens. Just give it a try!

**Comment by syssi** [comment]
Which version of the device do you own? The transparent one?

**Comment by syssi** [comment]
As first step could you provide the output of `mirobo discover`? Is the device discoverable by mDNS?

**Comment by subzero79** [comment]
Yesterday I’ve added philips.light.candle2 to xiaomi_miio.py. I’ve use the same transformation token command and seems to work. I can change brightness and temp. 
Add support seems to be trivial. 
Using homebridge worked immediately to because I needed to link it to some buttons. 

I’ll try to retrieve the you requested information early tomorrow.

**Comment by subzero79** [comment]
And yes is te transparent candle. Caveat.. the bulb makes a hiss noise when brightness goes below some level or is turn off. Noise stays for a few minutes.

**Comment by syssi** [comment]
Cool! I've added the device to this PR: https://github.com/home-assistant/home-assistant/pull/12883

I hope the PR will be merged into HA 0.66.
