### ISSUE TITLE
Document new vacuum features (goto, zoned cleaning)

### ISSUE THREAD

**Issue by SebRut** [rytilahti/python-miio#307]
Recently the Mi Home App added support for region cleaning and navigation to target like the V2 for V1. Is support planned for these features and is there any way to help develop these?

**Comment by rytilahti** [comment]
At the moment there is no easy way to get a map / coordinates from a non-rooted device, and the map itself is generated on the fly for new runs, meaning that the coordinates may change between runs. What we could do is to add those commands (move to X, start cleaning region X,Y) if someone figures out how they work, but the problem with the coordinates is harder to solve.

**Comment by rytilahti** [comment]
https://github.com/home-assistant/home-assistant/issues/13879 The commands are `app_goto_target` and `app_zoned_clean` apparently, as mentioned in additional information of that issue.

**Comment by ciB89** [comment]
When the map is created first, the starting location of the coordinates (where the robot sits at this moment) are always [25000,25000] and the rest of the map is then build around those coordinates. 
On the app you can then share/save the map (once it's complete). Use the "app_goto_target" command to figure out how much your robot moves with each coordinate change. Then create a grit with those coordinates on your image of the map and you can start creating areas/rooms. In theory - since the robot always starts from the same point and the map should not change as long as you don't move the station, this should work. It's a little bit of work, but other users from OpenHab/iobroker have reported that it works great. They had issues with the map randomly rotating 90 degrees, but that seemed to only affect a few people.

**Comment by ciB89** [comment]
Im a complete newbie, I have only used guthub passively so far and never programmed in python. I gave it a shot anyway. So don't be too hard on me :) #310

**Comment by ciB89** [comment]
Sure, I'll follow up on that :)

**Comment by rytilahti** [comment]
Any update on this? Any ideas on #355?

**Comment by ciB89** [comment]
I'm really sorry, I've recently accepted a job offer which is currently eating all of my time.. it's on my list, but I honestly can't tell when I have time to write something up. I think I can help with the referenced issue though.
