### ISSUE TITLE
could you pls add support to gateway's functions of security and light?

### ISSUE THREAD

**Issue by xcray** [rytilahti/python-miio#340]
As we know that the LAN API doesn't support controlling of the gw's security function (arming on/off, arming_wait_time) while miio interface does, so I think it's proper to use HA to control the security function, we need your help on python-miio codes.
There is a plugin of homebridge, [homebridge-mi-gateway-security](https://github.com/YinHangCode/homebridge-mi-gateway-security) for same function, maybe could been taken as reference.
About the gateway's light, although HA can control it via the LAN API (xiaomi_aqara), but there is a problem that the official Mijia App will lost control of the light ([the issue](https://github.com/home-assistant/home-assistant/issues/15005)). Since miio interface can also interact with the light function of gw, I guess it could be a better choice.

Anyway, thanks very much for your cool repository!

**Comment by rytilahti** [comment]
I have a list of potential commands and a barebone implementation, but the effort to add a proper support would be quite large (currently counting 73 commands, no idea if all of it works..). If someone wants to work on it I may find some time to put it all into a somewhat readable state, however, as @syssi said, I would not be expecting this to get used by the HA at any point due to duplication of functionality and therefore it is not really a priority.

**Comment by syssi** [comment]
@xcray Take a look at my custom_component: https://github.com/syssi/xiaomi_raw/

It provides a switch platform (switch.xiaomi_raw_miio) which can be used to switch/toggle individual methods of the MiIO API. It should be possible to control the alarm and the light.

**Comment by xcray** [comment]
@syssi @rytilahti Thanks for your comments. Anyhow, it's my honor to having received your replies!
Just for now, I don't think it's a good idea to completely get rid of official app and cloud.
In my opinion, HA's capability to control the arming mode of xiaomi gateway is necessary, especially for the scene all of my family are out of home.
I'll try your custom component on my host, so this issue could be closed.
Thanks again for your cool codes!
