### ISSUE TITLE
Get the map from Mi Vacuum V1?

### ISSUE THREAD

**Issue by jockebq** [rytilahti/python-miio#356]
Hi,

Would it be possible to get the map from the Mi Vacuum V1 and integrate to Home Assistant?
I found a thread on Home Assistant forums, but it requires root of the vacuum.
Can you somehow get the map from Xiaomi servers?

Thank you!

**Comment by rytilahti** [comment]
So, my understanding is that this would simulate the app and access xiaomi's servers to download the information to build a map. I won't accept such logic in python-miio, but if someone wants to create an external library to achieve that, I'm open to accept adding a command to access that library.

**Comment by jockebq** [comment]
I understand!
But is there any chance for integration of locally pulling the maps from the vacuum? That way you only need to root the vacuum and not setup the rest.

**Comment by rytilahti** [comment]
That's planned and currently WIP, so stay tuned. What is currently unsolved is how to transport the maps from the devices in an easy manner -- I may do a temporary hack to use ssh to fetch the database file until we have a nicer solution for that.

**Comment by lance36** [comment]
can you link the thread you mentioned ?

**Comment by rytilahti** [comment]
https://community.home-assistant.io/t/add-map-to-xiaomi-vacuum-cleaner/33155

**Comment by lance36** [comment]
@rytilahti tried it.
Works good.

**Comment by mlevit** [comment]
@rytilahti has there been any progress regarding this feature?

**Comment by rytilahti** [comment]
Alas no, there is no easy way to implement this. The best what can be done is to use Valetudo on a rooted device, which provides an API for fetching the current map: https://github.com/Hypfer/Valetudo#remote-api

**Comment by lance36** [comment]
Please be aware that there is a memory leak bug for the HA implementation
https://github.com/Hypfer/Valetudo/issues/39

**Comment by mlevit** [comment]
@rytilahti do we know how the FloleVac Android app manages to retrieve the map? I think someone commented within the HA community that it does so via the web and not locally with the vacuum.

**Comment by rytilahti** [comment]
@lance36 is that still a problem? Does it happen when using `returnImage`? Also, it looks like there is some built-in logic to remove old files to avoid filling the ram when not using `returnImage`: https://github.com/Hypfer/Valetudo/blob/master/webserver/WebServer.js#L713

@mlevit no idea really, but I think I was told at some point that flolevac does have some connectivity to the cloud (e.g., for fetching the token for local use), so that sounds a plausible way for it. However, tbh, I don't know for sure as I never used that app. To my knowledge there is no way to get access to that data without either 1) accessing the xiaomi services, 2) reading the log files from the device (as is done by valetudo), or 3) capturing the state updates the app sends to the cloud (related to https://github.com/Hypfer/Valetudo/issues/86).

**Comment by lance36** [comment]
@rytilahti i was watching memory usage of the process and it keep increasing steadily as more and more image requests were processed.
I implemented both the workarounds suggested by @dugite-code in https://github.com/Hypfer/Valetudo/issues/39

but the issue looks like it won't be fixed by the developers as they are looking for other ways to do this.

**Comment by dugite-code** [comment]
@lance36 Valetudo introduced MQTT support and you have to get the map that way, rather than with a web request.

My initial tests suggest the memory leak is now solved.

**Comment by lance36** [comment]
oh boy, that looks good. i'll try it out

**Comment by rytilahti** [comment]
There is not much we can do here, so I'll close this.
