### ISSUE TITLE
How to connect a device to WIFI without MiHome app  |  Can I connect a device to WIFI using Raspberry Pi?  #help wanted #Support

### ISSUE THREAD

**Issue by kim-sunghoon** [rytilahti/python-miio#609]
Hello, Thank you for the nice open-source!
I bought the Xiomi Plug v3 to help older people who do not have a smartphone. 
But I found out that connecting the device to wifi network seems to be impossible without MiHome app.

Is there any way can I connect the device to wifi with a Raspberry Pi or a PC? 

Thank you in advance!

**Comment by rytilahti** [comment]
Unfortunately there is no way to do the initial provisioning without the app, as far as I know. The problem lies in the fact that the initial token gets reinitialized during the provisioning process and the new token cannot be extracted from the device.

Changing the AP after obtaining the long-term token can be done using `configure-wifi` command after the initial pairing.
