### ISSUE TITLE
Add support for lumi.acpartner.mcn02 please?

### ISSUE THREAD

**Issue by ihaettypo** [rytilahti/python-miio#637]
The most affordable Xiaomi AC Companion right now. Please add support thanks.

**Comment by tcwj2008** [comment]
@rytilahti I have this device, is there anything that I can do

**Comment by wzhd** [comment]
Mine just arrived and I did a little packet capturing.

It first did an HTTP request:

> GET /gslb?dm=ots.io.mi.com HTTP/1.1
> Host: dns.io.mi.com
> User-Agent: MIoT

The `User-Agent` is particularly concerning. The reply contains just a few IPs:

> {"info":{"host_list":[{"ip":"\<redacted>","port":443},{"ip":"\<redacted>","port":443},{"ip":"\<redacted>","port":443}],"enable":1},"sign":\<redacted>","timestamp":"1580070784"}

The rest are mostly TLSv1.2 communications with one of the returned IPs. The server name is `Mijia Cloud`.

![image](https://user-images.githubusercontent.com/3471744/82576943-e36dc400-9bbc-11ea-983e-981da5025250.png)

It did send some UDP packets from source port 54321 to dest port 8053.

I wonder whether it's a miot device.

**Comment by rytilahti** [comment]
If you can obtain the token, you could try to execute `miot_info` command to see how is it responding. If it is a miot device, it will (hopefully) respond to that call.

The miot support is still WIP and there are a couple of PRs where the work is being done, but if it's a miot device, we can use the description files to help adding a preliminary support for that device. Otherwise it will require deciphering that udp device communication (which can be useful anycase, as the description files are not always complete).

**Comment by rezmus** [comment]
it's miio device

https://cdn.cnbj1.fds.api.mi-img.com/rn-plugins/2019-12-26/signed_10032_1000741_15_ANDROID_bundle_6f61e13511ab120a80f23e852aba4d8a.zip

**Comment by tcwj2008** [comment]
execute miiocli device info, it respond this

Model: lumi.acpartner.mcn02
Hardware version: esp32
Firmware version: 2.0.8_0002
Network: {'localIp': '192.168.1.111', 'mask': '255.255.255.0', 'gw': '192.168.1.1'}
AP: {'ssid': 'mywifi', 'bssid': '11:22:33:44:55:66', 'rssi': -56, 'primary': 1}
