### ISSUE TITLE
Smart Mi Standing fan 3 (Xiaomi Pedestal Fan 3, zhimi.fan.za5)

### ISSUE THREAD

**Issue by minseokhappylee** [rytilahti/python-miio#788]
Before submitting a new request, use the search to see if there is an existing issue for the device.

**Device information:**

  - Name(s) of the device: Smart mi standing fan 3
  - Link: https://en.techreviewer.de/xiaomi-smartmi-standing-fan-3/

Use `miiocli device --ip <ip address> --token <token>`.

  - Model: zhimi.fan.za5
  - Hardware version: esp32
  - Firmware version: 2.0.9

**Additional context**
If you know already about potential commands or any other useful information to add support for the device, please add that information here.

**Comment by rezmus** [comment]
miotspec.

**Comment by RockyLim92** [comment]
Is there any plan for supporting zhimi.fan.za5 or any workaround for supporting it?

Thank you

**Comment by al-one** [comment]
Try https://github.com/al-one/hass-xiaomi-miot

**Comment by gordon-zhao** [comment]
Quick updates:
I reviewed the miot-spec of this fan, but the specification is a huge mess (look at the custom-service). We definitely need a new mapping to custom services for some basic fan services (e.g. left/right turn, speed level, ac state). 

Besides, the left/right turn service (urn:zhimi-spec:property:swing-step-move:00000003:zhimi-za5:1) is different from the "motor-control" service seen in dmaker fans. It receives string instead of int, and there is no document about what strings it will receive. With a bit of guessing, here are some strings it receives: ["left", "right"]. On my device, it will turn left/right accordingly if I send these strings.

**Comment by ha0y** [comment]
This device is tested fully supported by https://github.com/ha0y/xiaomi_miot_raw .
