### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by rytilahti** [rytilahti/python-miio#88]
The unit test coverage of the library could use some love, maybe someone wants to pick a task to do some hacktoberfest good. Feel free to choose what you want to work! Current state is visible at https://coveralls.io/github/rytilahti/python-miio?branch=master .

**Comment by arekbulski** [comment]
Someone suggested that maybe you should have a test suite for construct, let me give you two opposite answers with reasons: Yes, because construct never promised backwards/forwards compatibility. API changes whenever there is a good reason to change it. But from this point forward, I will make best effort to get your code uptodate with every release. So No as in no need?

**Comment by rytilahti** [comment]
This issue is about tests on our inner workings & the interface we are providing to our downstreams, it's not about testing our dependencies per se.
